const RAW=[
["dz","Algeria","Algiers","AF",2,"grw","The biggest country in Africa, and most of it is the Sahara Desert."],
["ao","Angola","Luanda","AF",3,"kry","Its flag shows a machete and half a gear wheel."],
["bj","Benin","Porto-Novo","AF",4,"gry","Home of the ancient Kingdom of Dahomey and its famous women warriors."],
["bw","Botswana","Gaborone","AF",3,"bkw","Has more elephants than any other country on Earth."],
["bf","Burkina Faso","Ouagadougou","AF",4,"gry","Its name means 'Land of Honest People'."],
["bi","Burundi","Gitega","AF",4,"grw","Its royal drummers are so famous they are a world treasure."],
["cv","Cape Verde","Praia","AF",4,"brwy","Ten islands off Africa's coast with beaches and a volcano."],
["cm","Cameroon","Yaoundé","AF",2,"gry","Called 'Africa in miniature' because it has jungles, deserts, beaches and mountains."],
["cf","Central African Republic","Bangui","AF",4,"bgrwy","One of the most colorful flags in the world, with five colors."],
["td","Chad","N'Djamena","AF",3,"bry","Its flag looks almost exactly like Romania's flag!"],
["km","Comoros","Moroni","AF",4,"bgrwy","Four stars and four stripes for four islands."],
["cg","Republic of the Congo","Brazzaville","AF",4,"gry","Its capital sits right across the river from another capital, Kinshasa."],
["cd","DR Congo","Kinshasa","AF",3,"bry","Home of the bonobo, a rare ape found nowhere else."],
["ci","Ivory Coast","Yamoussoukro","AF",2,"gow","It's Ireland's flag flipped around, with orange first!"],
["dj","Djibouti","Djibouti","AF",4,"bgrw","One of the hottest places on the planet."],
["eg","Egypt","Cairo","AF",1,"krwy","The pyramids here are more than 4,500 years old!"],
["gq","Equatorial Guinea","Malabo","AF",4,"bgrw","Its flag has a silk-cotton tree in the middle."],
["er","Eritrea","Asmara","AF",4,"bgry","An olive branch sits on its red triangle."],
["sz","Eswatini","Mbabane","AF",4,"bkrwy","Its flag shows a shield, two spears and a fighting stick."],
["et","Ethiopia","Addis Ababa","AF",2,"bgry","Coffee was first discovered here, by a goat herder!"],
["ga","Gabon","Libreville","AF",4,"bgy","Almost 90% of the country is rainforest."],
["gm","Gambia","Banjul","AF",4,"bgrw","The smallest country on mainland Africa, shaped like a river."],
["gh","Ghana","Accra","AF",2,"gkry","The black star stands for African freedom."],
["gn","Guinea","Conakry","AF",3,"gry","It's Mali's flag in reverse order!"],
["gw","Guinea-Bissau","Bissau","AF",4,"gkry","Made of dozens of islands and a mainland."],
["ke","Kenya","Nairobi","AF",1,"gkrw","Famous for lions, giraffes and the world's fastest marathon runners."],
["ls","Lesotho","Maseru","AF",4,"bgkw","A country completely surrounded by South Africa."],
["lr","Liberia","Monrovia","AF",3,"brw","Its flag looks like the USA's, with just one star."],
["ly","Libya","Tripoli","AF",3,"gkrw","The Sahara Desert covers most of the country."],
["mg","Madagascar","Antananarivo","AF",2,"grw","Lemurs live here and nowhere else in the wild!"],
["mw","Malawi","Lilongwe","AF",4,"gkr","A rising sun shines on its flag."],
["ml","Mali","Bamako","AF",3,"gry","Timbuktu was once a city of gold and thousands of books."],
["mr","Mauritania","Nouakchott","AF",4,"gry","A golden crescent moon and star on green."],
["mu","Mauritius","Port Louis","AF",3,"bgry","The dodo bird used to live here."],
["ma","Morocco","Rabat","AF",2,"gr","A green star on a red flag."],
["mz","Mozambique","Maputo","AF",4,"gkrwy","The only flag in the world with a modern rifle on it."],
["na","Namibia","Windhoek","AF",3,"bgrwy","Has some of the tallest sand dunes in the world."],
["ne","Niger","Niamey","AF",4,"gow","An orange sun in the middle of the flag."],
["ng","Nigeria","Abuja","AF",1,"gw","More people live here than in any other African country."],
["rw","Rwanda","Kigali","AF",3,"bgy","Land of the mountain gorillas."],
["st","São Tomé and Príncipe","São Tomé","AF",4,"gkry","Two tiny islands right on the equator."],
["sn","Senegal","Dakar","AF",2,"gry","A green star sits in the middle of the yellow stripe."],
["sc","Seychelles","Victoria","AF",3,"bgrwy","Its flag looks like rays of a colorful sunrise."],
["sl","Sierra Leone","Freetown","AF",4,"bgw","Its name means 'Lion Mountains'."],
["so","Somalia","Mogadishu","AF",3,"bw","One white star on a light blue flag."],
["za","South Africa","Pretoria","AF",1,"bgkrwy","Six colors! One of the most colorful flags in the world."],
["ss","South Sudan","Juba","AF",4,"bgkrwy","The newest country in the world, born in 2011."],
["sd","Sudan","Khartoum","AF",3,"gkrw","Has more pyramids than Egypt!"],
["tz","Tanzania","Dodoma","AF",2,"bgky","Home of Mount Kilimanjaro, the tallest mountain in Africa."],
["tg","Togo","Lomé","AF",4,"grwy","A thin country only about 50 miles wide."],
["tn","Tunisia","Tunis","AF",2,"rw","Looks like Turkey's flag, but with a white circle."],
["ug","Uganda","Kampala","AF",2,"kry","A crested crane bird stands in the center."],
["zm","Zambia","Lusaka","AF",3,"gkor","Home to Victoria Falls, with an eagle on the flag."],
["zw","Zimbabwe","Harare","AF",2,"gkrwy","A stone bird from the ancient city of Great Zimbabwe."],
["am","Armenia","Yerevan","AS",3,"bor","One of the oldest countries in the world."],
["az","Azerbaijan","Baku","AS",3,"bgr","Called the Land of Fire: natural gas flames burn out of the ground."],
["bh","Bahrain","Manama","AS",3,"rw","A zigzag edge with five white points."],
["bd","Bangladesh","Dhaka","AS",2,"gr","A red circle on green, home of the Bengal tiger."],
["bt","Bhutan","Thimphu","AS",3,"oy","A dragon on the flag! It's called the Land of the Thunder Dragon."],
["bn","Brunei","Bandar Seri Begawan","AS",4,"kry","A tiny, rich country on the island of Borneo."],
["kh","Cambodia","Phnom Penh","AS",2,"brw","The only flag with a building on it: the temple of Angkor Wat."],
["cn","China","Beijing","AS",1,"ry","Home of the Great Wall and giant pandas."],
["cy","Cyprus","Nicosia","EU",3,"gow","Its flag shows the shape of the island itself."],
["ge","Georgia","Tbilisi","AS",3,"rw","Five red crosses on white."],
["in","India","New Delhi","AS",1,"bgow","A blue wheel with 24 spokes sits in the middle."],
["id","Indonesia","Jakarta","AS",2,"rw","More than 17,000 islands! Its flag looks just like Monaco's."],
["ir","Iran","Tehran","AS",2,"grw","Once called Persia, famous for beautiful carpets."],
["iq","Iraq","Baghdad","AS",2,"gkrw","Some of the very first cities in the world were built here."],
["il","Israel","Jerusalem","AS",1,"bw","A blue star of David between two blue stripes."],
["jp","Japan","Tokyo","AS",1,"rw","The red circle is the rising sun."],
["jo","Jordan","Amman","AS",2,"gkrw","Home of Petra, a city carved into pink rock."],
["kz","Kazakhstan","Astana","AS",2,"by","A golden eagle flies under a golden sun."],
["kw","Kuwait","Kuwait City","AS",2,"gkrw","A tiny country with huge oil fields."],
["kg","Kyrgyzstan","Bishkek","AS",4,"ry","A sun with the roof of a yurt tent inside it."],
["la","Laos","Vientiane","AS",3,"brw","A white moon over the Mekong River."],
["lb","Lebanon","Beirut","AS",2,"grw","A green cedar tree in the center."],
["my","Malaysia","Kuala Lumpur","AS",2,"brwy","14 stripes and a 14-point star."],
["mv","Maldives","Malé","AS",3,"grw","The flattest country on Earth, made of 1,200 tiny islands."],
["mn","Mongolia","Ulaanbaatar","AS",2,"bry","The homeland of Genghis Khan and wild horses."],
["mm","Myanmar","Naypyidaw","AS",3,"gry","A big white star over three stripes."],
["np","Nepal","Kathmandu","AS",2,"brw","The only flag that isn't a rectangle! Home of Mount Everest."],
["kp","North Korea","Pyongyang","AS",3,"brw","A red star in a white circle."],
["om","Oman","Muscat","AS",3,"grw","Two crossed swords and a dagger on the flag."],
["pk","Pakistan","Islamabad","AS",2,"gw","A crescent moon and star on green."],
["ph","Philippines","Manila","AS",2,"brwy","If it's flown upside down, it means the country is at war!"],
["qa","Qatar","Doha","AS",2,"rw","Nine white points on a dark red flag."],
["sa","Saudi Arabia","Riyadh","AS",1,"gw","A sword and Arabic writing on green."],
["sg","Singapore","Singapore","AS",2,"rw","A city that is also a whole country."],
["kr","South Korea","Seoul","AS",1,"bkrw","The red and blue circle stands for balance."],
["lk","Sri Lanka","Sri Jayawardenepura Kotte","AS",2,"gory","A golden lion holding a sword."],
["tw","Taiwan","Taipei","AS",2,"brw","A white sun with 12 rays, one for each hour of the day."],
["tj","Tajikistan","Dushanbe","AS",4,"grwy","A golden crown with seven stars."],
["th","Thailand","Bangkok","AS",1,"brw","Land of smiles, elephants and golden temples."],
["tl","Timor-Leste","Dili","AS",4,"kry","One of the youngest countries in Asia."],
["tr","Turkey","Ankara","AS",1,"rw","A crescent and star. Its biggest city sits on two continents!"],
["tm","Turkmenistan","Ashgabat","AS",4,"grw","Carpet patterns are woven right into the flag!"],
["ae","United Arab Emirates","Abu Dhabi","AS",2,"gkrw","Home of the tallest building in the world."],
["uz","Uzbekistan","Tashkent","AS",3,"bgrw","Twelve stars and a crescent moon."],
["vn","Vietnam","Hanoi","AS",1,"ry","A big yellow star on red."],
["ye","Yemen","Sana'a","AS",3,"krw","Three simple stripes: red, white and black."],
["al","Albania","Tirana","EU",3,"kr","A black two-headed eagle on red."],
["ad","Andorra","Andorra la Vella","EU",3,"bry","A tiny country in the mountains between France and Spain."],
["at","Austria","Vienna","EU",2,"rw","Mozart's home country."],
["by","Belarus","Minsk","EU",3,"grw","A folk pattern runs down the side of the flag."],
["be","Belgium","Brussels","EU",2,"kry","Famous for waffles, fries and chocolate."],
["ba","Bosnia and Herzegovina","Sarajevo","EU",3,"bwy","A yellow triangle and a line of stars."],
["bg","Bulgaria","Sofia","EU",2,"grw","Grows most of the world's rose oil for perfume."],
["hr","Croatia","Zagreb","EU",2,"brw","A red-and-white checkerboard shield."],
["cz","Czechia","Prague","EU",2,"brw","A blue triangle points into white and red."],
["dk","Denmark","Copenhagen","EU",1,"rw","The oldest flag still in use, more than 800 years old!"],
["ee","Estonia","Tallinn","EU",2,"bkw","Blue, black and white for sky, soil and snow."],
["fi","Finland","Helsinki","EU",1,"bw","Land of a thousand lakes and Santa's Lapland."],
["fr","France","Paris","EU",1,"brw","Home of the Eiffel Tower!"],
["de","Germany","Berlin","EU",1,"kry","Black, red and gold stripes."],
["gr","Greece","Athens","EU",1,"bw","Nine stripes and a cross. The Olympics started here."],
["hu","Hungary","Budapest","EU",2,"grw","Its capital is two cities, Buda and Pest, joined by a river."],
["is","Iceland","Reykjavík","EU",2,"brw","Land of volcanoes, glaciers and hot springs."],
["ie","Ireland","Dublin","EU",1,"gow","Green, white and orange, in that order."],
["it","Italy","Rome","EU",1,"grw","Pizza and pasta were invented here!"],
["xk","Kosovo","Pristina","EU",4,"bwy","A map of the country and six stars."],
["lv","Latvia","Riga","EU",2,"rw","A dark red flag with a thin white stripe."],
["li","Liechtenstein","Vaduz","EU",3,"bry","A tiny country with a golden crown on its flag."],
["lt","Lithuania","Vilnius","EU",2,"gry","Yellow, green and red stripes."],
["lu","Luxembourg","Luxembourg","EU",2,"brw","Looks like the Netherlands' flag but with lighter blue."],
["mt","Malta","Valletta","EU",3,"rw","A George Cross medal in the corner."],
["md","Moldova","Chișinău","EU",3,"bry","An eagle holding a shield in the middle."],
["mc","Monaco","Monaco","EU",2,"rw","The second-smallest country, famous for race cars."],
["me","Montenegro","Podgorica","EU",3,"ry","A golden eagle on red with a golden border."],
["nl","Netherlands","Amsterdam","EU",1,"brw","Tulips, windmills and lots of bicycles."],
["mk","North Macedonia","Skopje","EU",3,"ry","A sun with eight rays."],
["no","Norway","Oslo","EU",1,"brw","Land of fjords and the northern lights."],
["pl","Poland","Warsaw","EU",1,"rw","White on top, red on the bottom."],
["pt","Portugal","Lisbon","EU",1,"gry","Great explorers sailed from here 500 years ago."],
["ro","Romania","Bucharest","EU",2,"bry","Home of Transylvania, where the Dracula story comes from."],
["ru","Russia","Moscow","EU",1,"brw","The biggest country in the world."],
["sm","San Marino","San Marino","EU",4,"bw","One of the oldest republics in the world."],
["rs","Serbia","Belgrade","EU",2,"brw","A two-headed eagle on its shield."],
["sk","Slovakia","Bratislava","EU",2,"brw","Three mountains and a cross on its shield."],
["si","Slovenia","Ljubljana","EU",2,"brw","Its shield shows a mountain and three stars."],
["es","Spain","Madrid","EU",1,"ry","Red and yellow, flamenco and football!"],
["se","Sweden","Stockholm","EU",1,"by","A yellow cross on blue."],
["ch","Switzerland","Bern","EU",1,"rw","One of only two square flags in the world."],
["ua","Ukraine","Kyiv","EU",1,"by","Blue sky over golden wheat fields."],
["gb","United Kingdom","London","EU",1,"brw","The Union Jack combines three crosses."],
["va","Vatican City","Vatican City","EU",2,"wy","The smallest country in the world."],
["ag","Antigua and Barbuda","St. John's","NA",4,"bkrwy","365 beaches, one for every day of the year!"],
["bs","Bahamas","Nassau","NA",2,"bky","Swimming pigs live on one of its islands."],
["bb","Barbados","Bridgetown","NA",3,"bky","A broken trident on the flag."],
["bz","Belize","Belmopan","NA",3,"brw","The only flag with people on it."],
["ca","Canada","Ottawa","NA",1,"rw","A red maple leaf."],
["cr","Costa Rica","San José","NA",2,"brw","Home to sloths, toucans and rainforests."],
["cu","Cuba","Havana","NA",1,"brw","A white star in a red triangle."],
["dm","Dominica","Roseau","NA",4,"gkprwy","A purple parrot on the flag!"],
["do","Dominican Republic","Santo Domingo","NA",2,"brw","The only flag with a Bible on it."],
["sv","El Salvador","San Salvador","NA",2,"bw","Its name means 'The Savior'."],
["gd","Grenada","St. George's","NA",4,"gry","A nutmeg on the flag. It's called the Spice Island."],
["gt","Guatemala","Guatemala City","NA",2,"bw","A quetzal bird sits on the flag."],
["ht","Haiti","Port-au-Prince","NA",2,"brw","The first country founded by formerly enslaved people."],
["hn","Honduras","Tegucigalpa","NA",2,"bw","Five stars for five Central American countries."],
["jm","Jamaica","Kingston","NA",1,"gky","One of the only flags without red, white or blue."],
["mx","Mexico","Mexico City","NA",1,"grw","An eagle eating a snake on a cactus."],
["ni","Nicaragua","Managua","NA",3,"bw","A rainbow inside a triangle on its flag."],
["pa","Panama","Panama City","NA",2,"brw","The Panama Canal connects two oceans."],
["kn","Saint Kitts and Nevis","Basseterre","NA",4,"gkry","The smallest country in the Americas."],
["lc","Saint Lucia","Castries","NA",4,"bkwy","Two mountain peaks called the Pitons on the flag."],
["vc","Saint Vincent and the Grenadines","Kingstown","NA",4,"bgy","Three green diamonds in the middle."],
["tt","Trinidad and Tobago","Port of Spain","NA",3,"krw","Home of the steel drum and Carnival."],
["us","United States","Washington, D.C.","NA",1,"brw","50 stars for 50 states."],
["ar","Argentina","Buenos Aires","SA",1,"bwy","A smiling sun in the middle."],
["bo","Bolivia","Sucre","SA",2,"gry","Has a giant salt flat that looks like a mirror after rain."],
["br","Brazil","Brasília","SA",1,"bgwy","The Amazon rainforest and football!"],
["cl","Chile","Santiago","SA",2,"brw","One white star. It's a very long, thin country."],
["co","Colombia","Bogotá","SA",1,"bry","The yellow stripe is twice as tall as the others."],
["ec","Ecuador","Quito","SA",2,"bry","Named after the equator, which runs right through it."],
["gy","Guyana","Georgetown","SA",4,"gkrwy","Its flag is called the Golden Arrowhead."],
["py","Paraguay","Asunción","SA",2,"brw","The only flag with different pictures on each side."],
["pe","Peru","Lima","SA",2,"rw","Home of Machu Picchu, a city in the clouds."],
["sr","Suriname","Paramaribo","SA",4,"grwy","A big yellow star in the middle."],
["uy","Uruguay","Montevideo","SA",2,"bwy","A sun with a face in the corner."],
["ve","Venezuela","Caracas","SA",2,"bry","Home of Angel Falls, the tallest waterfall on Earth."],
["au","Australia","Canberra","OC",1,"brw","Kangaroos, koalas and the Southern Cross stars."],
["fj","Fiji","Suva","OC",3,"brwy","More than 300 islands in the Pacific."],
["ki","Kiribati","Tarawa","OC",4,"brwy","A frigatebird flying over the sunrise."],
["mh","Marshall Islands","Majuro","OC",4,"bow","Two rays shooting across a blue flag."],
["fm","Micronesia","Palikir","OC",4,"bw","Four white stars on blue for four island states."],
["nr","Nauru","Yaren","OC",4,"bwy","The third-smallest country in the world."],
["nz","New Zealand","Wellington","OC",1,"brw","Four red stars of the Southern Cross."],
["pw","Palau","Ngerulmud","OC",4,"by","A yellow full moon on blue."],
["pg","Papua New Guinea","Port Moresby","OC",3,"kry","A bird of paradise on the flag."],
["ws","Samoa","Apia","OC",3,"brw","Southern Cross stars in a blue corner."],
["sb","Solomon Islands","Honiara","OC",4,"bgwy","Five stars and a thin yellow stripe."],
["to","Tonga","Nukuʻalofa","OC",3,"rw","A red cross in the corner."],
["tv","Tuvalu","Funafuti","OC",4,"brwy","Nine stars for nine islands."],
["vu","Vanuatu","Port Vila","OC",4,"gkry","A boar's tusk on the flag."],
];
